global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
   - "linux_host_rules.yml"
   - "postgres_rules.yml"
   - "kafka_rules.yml"
   - "opensift_container_rules.yml"
   - "opensift_ufssession_rules.yml"
   - "haproxy_rules.yml"

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
          group: 'NT '
          service: 'MyLeg'

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'NT '
          service: 'MyLeg'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'NT '
          service: 'MyLeg'

  - job_name: 'jmeter'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9001']

